environment:
    global:
        PYTHON: "C:\\conda"
        MINICONDA_VERSION: "latest"
        PYTHON_ARCH: "64"

    matrix:
        - PYTHON_VERSION: "3.6"

matrix:
  fast_finish: true

platform:
  -x64

install:
  - "git clone git://github.com/astropy/ci-helpers.git"
  - "powershell ci-helpers/appveyor/install-miniconda.ps1"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "activate test"
  - "python -m pip install --upgrade pip"
  - "python -m pip install wheel"
  - "python -m pip install numpy scipy matplotlib scikit-learn pytest pyqt5 pyqtgraph"

build: false

test_script:
  - "%CMD_IN_ENV% python -m pytest tests"
