environment:
    global:
        PYTHON: "C:\\conda"
        MINICONDA_VERSION: "latest"
        PYTHON_ARCH: "64"
        CONDA_DEPENDENCIES: "numpy scipy scikit-learn setuptools pytest pyqt5 pyqtgraph"

    matrix:
        - PYTHON_VERSION: "3.6"

install:
  - "python -m pip install --upgrade pip"
  - "python -m pip install wheel"
  - "python -m pip install numpy scipy matplotlib scikit-learn pytest PyQt5 pyqtgraph"

build: off

test_script:
  - "%CMD_IN_ENV% python -m pytest"