environment:
  matrix:
      - PYTHON_VERSION: "3.5.0"
      - PYTHON_VERSION: "3.6.0"

install:
  - "python -m pip install --upgrade pip"
  - "python -m pip install wheel"
  - "python -m pip install numpy scipy matplotlib scikit-learn"

build: off

test_script:
  - "%CMD_IN_ENV% python -m pytest"