environment:
  matrix:
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"

install:
  - "%PYTHON%\\python.exe -m pip install --upgrade pip"
  - "%PYTHON%\\python.exe -m pip install wheel"
  - "%CMD_IN_ENV% pip install -r requirements.txt"

build: off

test_script:
  - "%CMD_IN_ENV% python -m pytest"